USE MYFIRSTDB;
select * from customer_data;
GO

SELECT TOP 5 *
FROM customer_data;

--Q1. What is the Total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer_data
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase ammount?
select customer_id,purchase_amount
from customer_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_data);

--Q3. which are the Top 5 products with the highest average review rating?
SELECT TOP 5
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS [Average Product Rating]
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--Q4. Compare the average purchase Amounts between Standard and Express shipping?
select shipping_type,
Round(avg(purchase_amount),2)
from customer_data
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as tota_customers,
ROUND(avg(purchase_amount),2) as average_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer_data
group by subscription_status
order by total_revenue , average_spend desc;

--Q6. Which 5 products have the highest percentage of purchase with discount applied?
select TOP 5 item_purchased,
    ROUND( 100 * SUM(CASE When discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
    from customer_data
    group by item_purchased
    order by discount_rate desc;

--Q7. segment customers into New,Returning, and Loyal based on their total 
--number of previous purchases, and show the count of each segment. 

with customer_type as (
 select customer_id, previous_purchases,
case 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases between 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer_data
)

select customer_segment, COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category order by count(customer_id) Desc) as item_rank
from customer_data
group by category,item_purchased 
)
select item_rank, category, item_purchased, total_orders 
from item_counts
where item_rank <= 3;

--Q9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
COUNT (customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status ;

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;
